"""English (en_us) language strings for Starfallen."""

BLOCKS = {
    "meteorite": "Meteorite",
    "molten_meteorite": "Molten Meteorite",
    "meteoric_iron_ore": "Meteoric Iron Ore",
    "meteoric_iron_block": "Block of Meteoric Iron",
    "starlit_crystal": "Starlit Crystal",
    "fallen_star": "Fallen Star",
    "astral_alloy_block": "Block of Astral Alloy",
    "voidsteel_block": "Block of Voidsteel",
    "astral_bricks": "Astral Bricks",
    "cracked_astral_bricks": "Cracked Astral Bricks",
    "chiseled_astral_bricks": "Chiseled Astral Bricks",
    "astral_brick_stairs": "Astral Brick Stairs",
    "astral_brick_slab": "Astral Brick Slab",
    "astral_brick_wall": "Astral Brick Wall",
    "astral_pillar": "Astral Pillar",
    "void_bricks": "Void Bricks",
    "cracked_void_bricks": "Cracked Void Bricks",
    "chiseled_void_bricks": "Chiseled Void Bricks",
    "void_brick_stairs": "Void Brick Stairs",
    "void_brick_slab": "Void Brick Slab",
    "void_brick_wall": "Void Brick Wall",
    "void_pillar": "Void Pillar",
    "starfield_tiles": "Starfield Tiles",
    "starlight_lamp": "Starlight Lamp",
    "spike_trap": "Spike Trap",
    "flame_jet": "Flame Jet",
    "sentinel_eye": "Sentinel Eye",
    "crumbling_void_bricks": "Crumbling Void Bricks",
    "astral_brazier": "Astral Brazier",
    "sanctum_seal": "Sanctum Seal",
    "seal_keystone": "Seal Keystone",
    "star_altar": "Star Altar",
    "astral_telescope": "Astral Telescope",
    "stellar_egg": "Stellar Egg",
}

ITEMS = {
    "raw_meteoric_iron": "Raw Meteoric Iron",
    "meteoric_iron_ingot": "Meteoric Iron Ingot",
    "meteoric_iron_nugget": "Meteoric Iron Nugget",
    "stardust": "Stardust",
    "star_fragment": "Star Fragment",
    "astral_alloy_ingot": "Astral Alloy Ingot",
    "molten_core": "Molten Core",
    "nebula_gel": "Nebula Gel",
    "void_essence": "Void Essence",
    "eclipse_shard": "Eclipse Shard",
    "voidsteel_ingot": "Voidsteel Ingot",
    "heart_of_astraeon": "Heart of Astraeon",
    "sigil_of_the_fallen_star": "Sigil of the Fallen Star",
    "starfall_beacon": "Starfall Beacon",
    "totem_of_the_fallen_star": "Totem of the Fallen Star",
    "star_tether": "Star Tether",
    "starseer_journal": "Starseer's Journal",
    "meteoric_sword": "Meteoric Sword",
    "meteoric_pickaxe": "Meteoric Pickaxe",
    "meteoric_axe": "Meteoric Axe",
    "meteoric_shovel": "Meteoric Shovel",
    "meteoric_hoe": "Meteoric Hoe",
    "starbreaker": "Starbreaker",
    "meteor_hammer": "Cratermaker",
    "nebula_blade": "Nebula Blade",
    "constellation_bow": "Constellation Bow",
    "riftblade": "Riftblade",
    "singularity_gauntlet": "Singularity Gauntlet",
    "starcaller_staff": "Starcaller Staff",
    "eclipse_scythe": "Eclipse Scythe",
    "meteoric_helmet": "Meteoric Helmet",
    "meteoric_chestplate": "Meteoric Chestplate",
    "meteoric_leggings": "Meteoric Leggings",
    "meteoric_boots": "Meteoric Boots",
    "starforged_helmet": "Starforged Helmet",
    "starforged_chestplate": "Starforged Chestplate",
    "starforged_leggings": "Starforged Leggings",
    "starforged_boots": "Starforged Boots",
    "voidwalker_helmet": "Voidwalker Hood",
    "voidwalker_chestplate": "Voidwalker Mantle",
    "voidwalker_leggings": "Voidwalker Greaves",
    "voidwalker_boots": "Voidwalker Treads",
    "halo_of_the_fallen_star": "Halo of the Fallen Star",
    "sanctum_chart": "Sanctum Chart",
    "star_wisp_spawn_egg": "Star Wisp Spawn Egg",
    "meteor_golem_spawn_egg": "Meteor Golem Spawn Egg",
    "void_stalker_spawn_egg": "Void Stalker Spawn Egg",
    "nebula_jelly_spawn_egg": "Nebula Jelly Spawn Egg",
    "starseer_spawn_egg": "Starseer Spawn Egg",
    "astral_mimic_spawn_egg": "Astral Mimic Spawn Egg",
    "comet_ray_spawn_egg": "Comet Ray Spawn Egg",
    "astraeon_spawn_egg": "Astraeon Spawn Egg",
}

ENTITIES = {
    "star_wisp": "Star Wisp",
    "meteor_golem": "Meteor Golem",
    "void_stalker": "Void Stalker",
    "nebula_jelly": "Nebula Jelly",
    "starseer": "Starseer",
    "high_starseer": "High Starseer",
    "astral_mimic": "Astral Mimic",
    "comet_ray": "Comet Ray",
    "astraeon": "Astraeon",
    "astraeon.title": "Astraeon, the Devouring Star",
    "astraeon.title_unbound": "Astraeon, Unbound",
    "meteor": "Meteor",
    "star_bolt": "Star Bolt",
    "star_arrow": "Star Arrow",
    "singularity": "Singularity",
    "thrown_scythe": "Eclipse Scythe",
    "tether_hook": "Star Tether",
    "molten_rock": "Molten Rock",
    "shockwave": "Shockwave",
}

# '!' = gold ability header, '~' = purple lore line, otherwise grey
TOOLTIPS = {
    "stardust": ["~Glittering remains of a shooting star.", "Befriends Star Wisps and Comet Rays.", "Lights Astral Braziers."],
    "star_fragment": ["~Still humming with the light of a dead sun."],
    "astral_alloy_ingot": ["~Meteoric iron, folded with starlight."],
    "molten_core": ["~It will not stop burning."],
    "nebula_gel": ["~Wobbles in time with distant galaxies."],
    "void_essence": ["~Cold. Silent. It watches you back."],
    "eclipse_shard": ["~A sliver of the sun's own shadow."],
    "voidsteel_ingot": ["~Forged where light goes to die."],
    "heart_of_astraeon": ["~The Devouring Star's heart still beats.", "Forges the Halo of the Fallen Star,", "the Eclipse Scythe and the Totem", "of the Fallen Star."],
    "sigil_of_the_fallen_star": ["~The key the Astral Order forged to", "~imprison what fell from the sky.", "!Use on the Star Altar", "Awakens Astraeon, the Devouring Star."],
    "starfall_beacon": ["!Use: Call a Starfall", "Meteors rain down around you", "for the next few minutes.", "~Needs the open sky."],
    "totem_of_the_fallen_star": ["!Supernova", "When you would die, you rise again", "in a blinding nova that hurls every", "nearby enemy away."],
    "star_tether": ["!Use: Fire the tether", "A grappling line of woven starlight.", "It pulls you to wherever it bites."],
    "starseer_journal": ["!Use: Read", "Everything you need to know", "about the stars that fell."],
    "meteoric_sword": ["!Searing Edge", "Still warm from re-entry:", "sets whatever it strikes ablaze."],
    "starbreaker": ["!Shatter", "Mines a 3x3 wall of stone.", "Sneak to mine a single block."],
    "meteor_hammer": ["!Hold Use: Wind up - release to leap", "Come down like a meteor. Damage grows", "with charge and fall height.", "Use in mid-air to dive straight down.",
                      "~No fall damage from a slam."],
    "nebula_blade": ["!Use: Starlight Dash", "Dash through your enemies. Everything", "you cut through is struck again by a", "Starlight Echo."],
    "constellation_bow": ["!Needs no arrows", "Looses bolts of starlight that home", "in on their target.", "!Sneak at full draw: Constellation Volley",
                          "Releases five stars at once."],
    "riftblade": ["!Use on a foe: Rift Strike", "Tear through space and strike it", "from behind for massive damage.", "A killing blow resets the cooldown -", "chain rifts from foe to foe."],
    "singularity_gauntlet": ["!Use: Singularity", "Hurls a seed of collapsed starlight that", "blooms into a black hole, drags enemies", "and loot into its heart, then implodes."],
    "starcaller_staff": ["!Use: Call Meteor", "A meteor strikes where you point.", "!Sneak + Use: Meteor Storm", "~Needs the open sky."],
    "eclipse_scythe": ["!Reaping Arc", "Every swing reaps a wide arc and", "drinks the life of the fallen.", "!Use: Hurl the scythe", "It carves through everything, then", "returns to your hand."],
    "halo_of_the_fallen_star": ["!Crown of living starlight", "Grants flight and starsight,", "and reveals every hostile creature", "nearby - even the ones in disguise."],
}

JOURNAL = [
    "\n§5§lThe Starseer's Journal§r\n\n§8Being a true account of the stars that fell, and of the thing that fell with them.\n\n\n§o- Brother Aldric,\nlast of the Astral Order",
    "§l§6Starfall§r\n\nOn some nights the sky breaks open. Meteors rain down, carving glowing craters and scattering §8Meteoric Iron§r, §eStardust§r and §bStarlit Crystals§r.\n\nA §6Starfall Beacon§r can call one down at will.",
    "§l§6Craters§r\n\nMine the §8Meteoric Iron Ore§r around a crater's heart. Large meteors leave a §6Fallen Star§r at their core: break it for §eStar Fragments§r.\n\nBeware - Meteor Golems sometimes ride the meteors down.",
    "§l§6Golden Meteors§r\nOnce in a while a meteor burns gold. Its crater is lined with gold, diamonds and emeralds.\n\n§l§bStellar Eggs§r\nSome large meteors carry an egg. Feed it §eStardust§r and it hatches into a §bComet Ray§r that is yours to ride.",
    "§l§6Forging§r\n\n§8Meteoric Iron§r\nSmelt Raw Meteoric Iron.\n\n§bAstral Alloy§r\n2 Meteoric Iron, 4 Stardust and 1 Star Fragment.\n\n§5Voidsteel§r\n2 Astral Alloy and 4 Void Essence.",
    "§l§6Star Armor§r\n\n§8Meteoric§r - land from a height to unleash a shockwave; magma cannot burn you.\n\n§bStarforged§r - double jump in mid-air.\n\n§5Voidwalker§r - press §lV§r to blink to wherever you look.",
    "§l§6Star Wisps§r\n\nLittle lights that drift down on clear nights. Offer one §eStardust§r and it may choose you: it fights at your side and mends your wounds.\n\n§l§dNebula Jellies§r\nHarmless... until struck.",
    "§l§bComet Rays§r\n\nGreat gliding rays that swim through the sky during a Starfall. Win one over with Stardust or a Star Fragment, then saddle up and ride the stars.\n\n§oJump§r to climb, §osprint§r to boost.",
    "§l§6Meteor Golems§r\n\nMolten giants born in the impact. They pound the earth and hurl burning rock.\n\nWhen the fire in their core runs low they §cOVERHEAT§r - that is your moment to strike.",
    "§4§lVoid Stalkers§r\n\nThey cannot move while you look at them.\n\nDo not look away.\n\nDo not blink.\n\nIf you hear it breathing behind you, it is already too late.",
    "§l§eStarseers§r\n\nCultists who worship the fallen star. They hurl star bolts and pull meteors down from the sky.\n\nTheir master, the §6High Starseer§r, keeps watch at the top of the §bAstral Observatory§r.",
    "§l§bThe Observatory§r\n\nA tower of pale bricks under open skies. Look through its great §6telescope§r and the stars will show you the way to the Sanctum.\n\nThe Observatory keeps more than one secret.\n\n§oMind the chests.",
    "§l§5The Sanctum§r\n\nBeneath a lonely obelisk lie halls of void brick: traps, watchers in the dark, and the §bSeal§r.\n\nLight all four §bAstral Braziers§r with Stardust, flint and steel or a fire charge to break it.",
    "§l§5The Sigil§r\n\nThe Order hid the §dSigil of the Fallen Star§r in a vault. Our librarians were very fond of secret doors.\n\nPlace the Sigil upon the §5Star Altar§r...\n\n§oonly if you are ready.",
    "§4§lAstraeon§r\n\nThe Devouring Star. It rains meteors, fires a beam that unmakes stone, slams the earth and births black holes.\n\nWounded, it breaks its chains - and at the very end it goes §6supernova§r.\n§lTake cover.",
    "§l§6Star Weapons§r\n\n§6Cratermaker§r: leap & slam\n§bNebula Blade§r: star dash\n§bConstellation Bow§r: homing stars\n§5Riftblade§r: strike from behind\n§5Singularity Gauntlet§r: black holes\n§6Starcaller Staff§r: call meteors",
    "§l§6The Heart§r\n\nFrom Astraeon's heart one may forge the §eHalo of the Fallen Star§r, the §5Eclipse Scythe§r, and the §6Totem of the Fallen Star§r - which turns your death into a supernova.",
    "\n\n\n§8§oIf you are reading this, the stars are falling again.\n\nLook up.\n\nSomething is looking back.",
]

BOOKS = {
    "observatory.title": "Observations, Vol. IX",
    "observatory.1": "Night 212.\n\nThe comet grows brighter every night. The High Starseer calls it a blessing.\n\nI am not so sure.",
    "observatory.2": "Night 219.\n\nThe great telescope has shown me where the old Sanctum lies. Anyone who looks through its lens will see it too.",
    "observatory.3": "Night 220.\n\nI have hidden my last notes where no one ever looks: beneath the red carpet.\n\nThe Starseers must not find them.",
    "sanctum.title": "On the Sanctum",
    "sanctum.1": "The Order built the Sanctum to hold what fell. Four braziers bind the Seal. While even one burns cold, the Seal holds.",
    "sanctum.2": "The vault keeps the Sigil, the only key to the altar. The way to it is hidden among the books.",
    "sanctum.3": "Should the altar ever wake, do not stand still. Its beam follows the eye.\n\nKeep moving.",
    "secret.title": "My Last Entry",
    "secret.1": "They know. The High Starseer means to wake Astraeon with the Sigil.\n\nI have carried what treasure I could down here.",
    "secret.2": "If you find this: take the egg. Raise the ray. They were the stars' children long before we came.\n\n- Aldric",
    "sanctum_lore.title": "The Fall",
    "sanctum_lore.1": "In the age before the Order, a star fell and did not die. It ate the light of everything around it.",
    "sanctum_lore.2": "Nine hundred of us gave our starlight to bind it. We named it Astraeon, and buried it beneath the Hall of Stars.",
    "sanctum_lore.3": "The Seal will hold for as long as the braziers stay cold.\n\nLet no one light them.",
    "hint.title": "A Librarian's Riddle",
    "hint.1": "Where knowledge is thickest, the wall is thinnest.\n\nSeek the shelf that is carved unlike all the rest.",
    "hint.2": "Behind it lies what we could not destroy.\n\n- Archivist Venn",
}

SIGNS = {
    "sanctum.1": "HERE LIES",
    "sanctum.2": "THE SANCTUM OF",
    "sanctum.3": "THE FALLEN STAR",
    "sanctum.4": "Turn back.",
    "seal.1": "LIGHT THE FOUR",
    "seal.2": "BRAZIERS OF",
    "seal.3": "THE SANCTUM TO",
    "seal.4": "BREAK THE SEAL",
}

ADVANCEMENTS = {
    "root": ("Starfallen", "The sky is falling - and something came with it"),
    "look_up": ("Look Up", "Witness a meteor crash to the ground"),
    "iron_from_the_sky": ("Iron From the Sky", "Obtain Raw Meteoric Iron"),
    "starforged": ("Starforged", "Forge an Astral Alloy Ingot"),
    "into_the_void": ("Into the Void", "Forge a Voidsteel Ingot"),
    "skyfall": ("Skyfall", "Slam into the ground with the Cratermaker after falling more than 12 blocks"),
    "wisp_friend": ("A Little Light", "Befriend a Star Wisp with Stardust"),
    "comet_rider": ("Comet Rider", "Tame a Comet Ray"),
    "stargazer": ("Stargazer", "Gaze through an Astral Telescope"),
    "the_high_seat": ("The High Seat", "Defeat the High Starseer atop the Astral Observatory"),
    "the_sanctum": ("Beneath the Obelisk", "Enter the Sanctum of the Fallen Star"),
    "dont_blink": ("Don't Blink", "Defeat a Void Stalker"),
    "surprise": ("Surprise!", "Get bitten by an Astral Mimic"),
    "the_sigil": ("The Key to the Sky", "Find the Sigil of the Fallen Star"),
    "seal_breaker": ("Seal Breaker", "Light the four braziers and break the Sanctum Seal"),
    "starfallen": ("Starfallen", "Defeat Astraeon, the Devouring Star"),
    "crown_of_stars": ("Crown of Stars", "Forge the Halo of the Fallen Star"),
    "reaper_of_suns": ("Reaper of Suns", "Forge the Eclipse Scythe"),
    "second_sunrise": ("Second Sunrise", "Cheat death with a Totem of the Fallen Star"),
}

DEATHS = {
    "spikes": ("%1$s was impaled by star-steel spikes", "%1$s was impaled by star-steel spikes while fleeing %2$s"),
    "starfire": ("%1$s was consumed by starfire", "%1$s was consumed by starfire while fighting %2$s"),
    "meteor": ("%1$s was flattened by a meteor", "%1$s was flattened by a meteor while fighting %2$s"),
    "star_bolt": ("%1$s was struck down by starlight from %2$s", "%1$s was struck down by starlight while fighting %2$s"),
    "void_rend": ("%1$s was torn apart by %2$s", "%1$s was torn apart by the void while fighting %2$s"),
    "astral_beam": ("%1$s was unmade by %2$s", "%1$s was unmade by starlight while fighting %2$s"),
    "shockwave": ("%1$s was flung into the air by %2$s", "%1$s was flung into the air while fighting %2$s"),
}

SUBTITLES = {
    "meteor_fall": "Meteor screams overhead",
    "meteor_impact": "Meteor impacts",
    "starfall_begin": "The sky shimmers",
    "star_chime": "Stars chime",
    "wisp_ambient": "Star Wisp twinkles",
    "wisp_hurt": "Star Wisp hurts",
    "wisp_death": "Star Wisp fades",
    "golem_ambient": "Meteor Golem grinds",
    "golem_hurt": "Meteor Golem cracks",
    "golem_death": "Meteor Golem crumbles",
    "golem_slam": "Meteor Golem slams",
    "stalker_ambient": "Something breathes",
    "stalker_scream": "Void Stalker screams",
    "stalker_hurt": "Void Stalker glitches",
    "stalker_death": "Void Stalker unravels",
    "jelly_ambient": "Nebula Jelly bubbles",
    "jelly_zap": "Nebula Jelly zaps",
    "starseer_ambient": "Starseer chants",
    "starseer_cast": "Starseer casts a spell",
    "starseer_hurt": "Starseer hurts",
    "starseer_death": "Starseer dies",
    "mimic_reveal": "Chest growls",
    "mimic_chomp": "Mimic chomps",
    "ray_ambient": "Comet Ray sings",
    "ray_boost": "Comet Ray surges",
    "astraeon_roar": "Astraeon roars",
    "astraeon_ambient": "Astraeon rumbles",
    "astraeon_hurt": "Astraeon hurts",
    "astraeon_death": "Astraeon collapses",
    "astraeon_beam_charge": "Astraeon charges a beam",
    "astraeon_beam": "Astral beam fires",
    "astraeon_slam": "Astraeon slams",
    "astraeon_awaken": "Astraeon awakens",
    "hammer_slam": "Cratermaker slams",
    "blade_dash": "Blade dashes",
    "rift_blink": "Space tears",
    "singularity_hum": "Singularity hums",
    "singularity_collapse": "Singularity implodes",
    "scythe_throw": "Scythe whirls",
    "tether_fire": "Tether fires",
    "star_bolt": "Star bolt flies",
    "totem_nova": "Supernova!",
    "double_jump": "Starstep",
    "spike_trap": "Spikes spring",
    "flame_jet": "Flames roar",
    "seal_break": "Seal shatters",
    "brazier_ignite": "Brazier ignites",
    "telescope_gaze": "Stars shimmer",
    "egg_hatch": "Stellar Egg hatches",
    "crystal_break": "Crystal shatters",
}

MISC = {
    "itemGroup.starfallen": "Starfallen",
    "key.categories.starfallen": "Starfallen",
    "key.starfallen.blink": "Voidwalker Blink",
    "effect.starfallen.starstruck": "Starstruck",
    "tooltip.starfallen.set_bonus": "Set Bonus: %s",
    "tooltip.starfallen.set.meteoric": "Impact Landing",
    "tooltip.starfallen.set.meteoric.desc": "Land from a height to unleash a shockwave. Immune to magma, half damage from fire.",
    "tooltip.starfallen.set.starforged": "Starstep",
    "tooltip.starfallen.set.starforged.desc": "Double jump in mid-air. Half damage from meteors.",
    "tooltip.starfallen.set.voidwalker": "Void Blink",
    "tooltip.starfallen.set.voidwalker.desc": "Press [V] to blink to wherever you look. Half damage from void and star magic.",
    "tooltip.starfallen.set.celestial": "Celestial",
    "tooltip.starfallen.set.celestial.desc": "Starlight answers to you.",
    "message.starfallen.welcome": "A strange journal has found its way into your pack... The stars have been restless lately.",
    "message.starfallen.altar_hint": "The altar hungers for the Sigil of the Fallen Star.",
    "message.starfallen.altar_busy": "Astraeon is already awake!",
    "message.starfallen.beacon_active": "A Starfall is already raging!",
    "message.starfallen.beacon_no_sky": "The beacon must see the open sky.",
    "message.starfallen.boss_defeated": "Astraeon has fallen. The sky is quiet once more... for now.",
    "message.starfallen.boss_immune": "Astraeon cannot be harmed right now!",
    "message.starfallen.brazier_hint": "Light it with Stardust, Flint and Steel or a Fire Charge.",
    "message.starfallen.egg_hatched": "The Stellar Egg hatched! A baby Comet Ray has bonded with you.",
    "message.starfallen.golden_meteor": "A Golden Meteor has landed nearby!",
    "message.starfallen.keystone_status": "The Seal holds: %s of %s braziers lit.",
    "message.starfallen.nova_warning": "ASTRAEON IS GOING SUPERNOVA - TAKE COVER!",
    "message.starfallen.rift_chain": "Rift chain!",
    "message.starfallen.seal_weakens": "The Seal weakens... (%s/%s braziers lit)",
    "message.starfallen.staff_no_sky": "The staff needs the open sky to call a meteor.",
    "message.starfallen.starfall_end": "The Starfall is over.",
    "message.starfallen.telescope_again": "The stars have already shown you the way.",
    "message.starfallen.telescope_chart": "Through the lens you glimpse the Sanctum of the Fallen Star, and sketch its location onto a chart.",
    "message.starfallen.telescope_meteor": "The stars answer your gaze...",
    "message.starfallen.telescope_nothing": "The sky reveals nothing. No Sanctum lies within reach.",
    "title.starfallen.starfall": "STARFALL",
    "title.starfallen.starfall.sub": "The sky is falling - look up!",
    "title.starfallen.seal_broken": "The Seal Is Broken",
    "title.starfallen.seal_broken.sub": "The Heart Chamber lies open...",
    "title.starfallen.astraeon": "ASTRAEON",
    "title.starfallen.astraeon.sub": "The Devouring Star",
    "title.starfallen.phase2": "UNBOUND",
    "title.starfallen.phase2.sub": "Astraeon tears free of its chains!",
    "title.starfallen.victory": "VICTORY",
    "title.starfallen.victory.sub": "The Devouring Star has fallen",
    "title.starfallen.high_starseer.sub": "Keeper of the Observatory",
    "command.starfallen.started": "A Starfall has begun!",
    "command.starfallen.stopped": "The Starfall has been stopped.",
    "command.starfallen.status_on": "A Starfall is raging right now.",
    "command.starfallen.status_off": "The sky is calm. No Starfall is active.",
    "command.starfallen.meteor": "Called down a %s meteor.",
    "command.starfallen.kit": "Here is the Starfallen %s kit!",
    "biome.starfallen.crater": "Crater",
    "structure.starfallen.sanctum": "Sanctum of the Fallen Star",
    "structure.starfallen.astral_observatory": "Astral Observatory",
}


def build():
    out = {}
    for k, v in BLOCKS.items():
        out[f"block.starfallen.{k}"] = v
    for k, v in ITEMS.items():
        out[f"item.starfallen.{k}"] = v
    for k, v in ENTITIES.items():
        out[f"entity.starfallen.{k}"] = v
    for item, lines in TOOLTIPS.items():
        for i, line in enumerate(lines):
            out[f"tooltip.starfallen.{item}.{i}"] = line
    for i, page in enumerate(JOURNAL):
        out[f"journal.starfallen.page.{i}"] = page
    for k, v in BOOKS.items():
        out[f"book.starfallen.{k}"] = v
    for k, v in SIGNS.items():
        out[f"sign.starfallen.{k}"] = v
    for k, (title, desc) in ADVANCEMENTS.items():
        out[f"advancements.starfallen.{k}.title"] = title
        out[f"advancements.starfallen.{k}.description"] = desc
    for k, (plain, player) in DEATHS.items():
        out[f"death.attack.starfallen.{k}"] = plain
        out[f"death.attack.starfallen.{k}.player"] = player
    for k, v in SUBTITLES.items():
        out[f"subtitles.starfallen.{k}"] = v
    out.update(MISC)
    return out
