"""
Starfallen entity model generator.

Each model is defined once here (parts, cubes, pivots, rotations, paint styles). The script
emits the Java LayerDefinition ("*Geometry.java") and paints UV-exact textures for every cube,
plus a matching emissive "_glow" texture. Run from the repository root:

    python3 tools/modelgen.py
"""
import math
import os
import random

from pixel import Canvas, Noise, ramp, mix, shade, clamp, random_walk_cracks

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA_DIR = os.path.join(ROOT, "src/main/java/net/starfallen/client/model/gen")
TEX_DIR = os.path.join(ROOT, "src/main/resources/assets/starfallen/textures/entity")


# ---------------------------------------------------------------------------------------------
# Model description
# ---------------------------------------------------------------------------------------------

class Cube:
    def __init__(self, origin, size, style, uv=None, inflate=0.0, mirror=False):
        self.origin = origin
        self.size = size
        self.style = style
        self.uv = uv
        self.inflate = inflate
        self.mirror = mirror


class Part:
    def __init__(self, name, pivot=(0, 0, 0), rot=(0, 0, 0), cubes=(), children=()):
        self.name = name
        self.pivot = pivot
        self.rot = rot
        self.cubes = list(cubes)
        self.children = list(children)


class Model:
    def __init__(self, cls, tex, parts, textures):
        self.cls = cls
        self.tex = tex
        self.parts = parts
        # textures: list of (file_name, style_overrides dict)
        self.textures = textures


def all_cubes(parts):
    for p in parts:
        for c in p.cubes:
            yield p, c
        yield from all_cubes(p.children)


def pack(model):
    """Shelf-pack every cube's UV footprint into the texture."""
    tw, th = model.tex
    cubes = [c for _, c in all_cubes(model.parts) if c.uv is None]
    order = sorted(cubes, key=lambda c: -(c.size[2] + c.size[1]))
    x = y = shelf = 0
    for c in order:
        w, h, d = c.size
        fw, fh = int(math.ceil(2 * (d + w))), int(math.ceil(d + h))
        if x + fw > tw:
            x = 0
            y += shelf
            shelf = 0
        if y + fh > th:
            raise SystemExit(f"{model.cls}: texture {tw}x{th} too small")
        c.uv = (x, y)
        x += fw
        shelf = max(shelf, fh)


def f(v):
    return f"{float(v)}F"


def emit_java(model):
    lines = []
    counter = [0]

    def emit_part(part, parent):
        var = f"p{counter[0]}"
        counter[0] += 1
        cubes = "CubeListBuilder.create()"
        for c in part.cubes:
            cubes += f".texOffs({c.uv[0]}, {c.uv[1]})"
            if c.mirror:
                cubes += ".mirror()"
            o, s = c.origin, c.size
            cubes += (f".addBox({f(o[0])}, {f(o[1])}, {f(o[2])}, {f(s[0])}, {f(s[1])}, {f(s[2])}, "
                      f"new CubeDeformation({f(c.inflate)}))")
            if c.mirror:
                cubes += ".mirror(false)"
        pv, rt = part.pivot, part.rot
        pose = f"PartPose.offsetAndRotation({f(pv[0])}, {f(pv[1])}, {f(pv[2])}, {f(rt[0])}, {f(rt[1])}, {f(rt[2])})"
        lines.append(f"        PartDefinition {var} = {parent}.addOrReplaceChild(\"{part.name}\", {cubes}, {pose});")
        for ch in part.children:
            emit_part(ch, var)

    for p in model.parts:
        emit_part(p, "root")
    body = "\n".join(lines)
    src = f"""package net.starfallen.client.model.gen;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/modelgen.py - edit the generator, not this file. */
@SuppressWarnings("unused")
public final class {model.cls}Geometry {{
    private {model.cls}Geometry() {{}}

    public static LayerDefinition create() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
{body}
        return LayerDefinition.create(mesh, {model.tex[0]}, {model.tex[1]});
    }}
}}
"""
    os.makedirs(JAVA_DIR, exist_ok=True)
    with open(os.path.join(JAVA_DIR, f"{model.cls}Geometry.java"), "w") as fh:
        fh.write(src)


# ---------------------------------------------------------------------------------------------
# Painting
# ---------------------------------------------------------------------------------------------

FACES = ("top", "bottom", "west", "north", "east", "south")


def face_rects(c):
    u, v = c.uv
    w, h, d = (int(math.ceil(s)) for s in c.size)
    return {
        "top": (u + d, v, w, d),
        "bottom": (u + d + w, v, w, d),
        "west": (u, v + d, d, h),
        "north": (u + d, v + d, w, h),
        "east": (u + d + w, v + d, d, h),
        "south": (u + 2 * d + w, v + d, w, h),
    }


class Ctx:
    def __init__(self, base, glow, x, y, w, h, face, cube, rng, noise, params):
        self.base, self.glow = base, glow
        self.x0, self.y0, self.w, self.h = x, y, w, h
        self.face, self.cube, self.rng, self.noise, self.p = face, cube, rng, noise, params

    def set(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.base.set(self.x0 + x, self.y0 + y, c)

    def glow_set(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.glow.set(self.x0 + x, self.y0 + y, c)

    def both(self, x, y, c):
        self.set(x, y, c)
        self.glow_set(x, y, c)

    def n(self, x, y, scale=0.35, octaves=3):
        return self.noise.fbm((self.x0 + x) * scale, (self.y0 + y) * scale, octaves)


def fill_noise(ctx, colors, scale=0.35, light=1.0):
    for y in range(ctx.h):
        for x in range(ctx.w):
            t = ctx.n(x, y, scale) * 0.85 + ctx.rng.random() * 0.15
            ctx.set(x, y, shade(ramp(colors, t), light))


def face_light(face):
    return {"top": 1.12, "bottom": 0.7, "north": 1.0, "south": 0.9, "west": 0.95, "east": 0.95}[face]


def cracks(ctx, count, length, dim, bright):
    for _ in range(count):
        x, y = ctx.rng.randrange(max(1, ctx.w)), ctx.rng.randrange(max(1, ctx.h))
        for _ in range(length):
            ctx.set(x, y, dim)
            ctx.glow_set(x, y, bright)
            r = ctx.rng.random()
            if r < 0.45:
                x += ctx.rng.choice((-1, 1))
            elif r < 0.9:
                y += ctx.rng.choice((-1, 1))
            else:
                x += ctx.rng.choice((-1, 1))
                y += 1


def speckle(ctx, chance, color, glow=True):
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.rng.random() < chance:
                if glow:
                    ctx.both(x, y, color)
                else:
                    ctx.set(x, y, color)


# ---- individual styles -----------------------------------------------------------------------

ROCK = [(26, 21, 20), (38, 31, 28), (52, 42, 37), (66, 54, 46), (80, 66, 55)]
VOID = [(6, 4, 16), (11, 7, 26), (18, 12, 40), (26, 17, 56), (34, 22, 70)]
OBSIDIAN = [(12, 8, 26), (20, 13, 40), (28, 18, 56), (38, 25, 72)]
NAVY = [(10, 18, 52), (16, 28, 74), (22, 38, 96), (30, 52, 120)]


def st_wisp_core(ctx):
    cx, cy = (ctx.w - 1) / 2, (ctx.h - 1) / 2
    for y in range(ctx.h):
        for x in range(ctx.w):
            d = math.hypot(x - cx, y - cy) / max(1, max(cx, cy))
            ctx.set(x, y, mix((255, 255, 255), (205, 210, 225), min(1, d)))
    if ctx.face == "north" and ctx.w >= 6:
        ex = ctx.w // 2
        for (x, y) in ((ex - 2, ctx.h // 2 - 1), (ex + 1, ctx.h // 2 - 1)):
            ctx.set(x, y, (40, 30, 70))
            ctx.set(x, y + 1, (40, 30, 70))
        ctx.set(ex - 1, ctx.h // 2 + 2, (90, 70, 120))
        ctx.set(ex, ctx.h // 2 + 2, (90, 70, 120))


def st_wisp_halo(ctx):
    cx, cy = (ctx.w - 1) / 2, (ctx.h - 1) / 2
    for y in range(ctx.h):
        for x in range(ctx.w):
            d = math.hypot(x - cx, y - cy) / max(1, max(cx, cy))
            a = clamp(95 * (1 - d) + 25)
            ctx.set(x, y, (255, 255, 255, a))
            if ctx.rng.random() < 0.06:
                ctx.set(x, y, (255, 255, 255, 190))


def st_mote(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.set(x, y, (255, 255, 250))


def st_wisp_tail(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            a = 230 if ctx.face in ("top", "bottom", "north") else 190
            ctx.set(x, y, (235, 238, 250, a))


def st_rock(ctx, core=False, head=False):
    fill_noise(ctx, ROCK, 0.3, face_light(ctx.face))
    cracks(ctx, max(1, ctx.w * ctx.h // 60), 6 + ctx.rng.randrange(6), (140, 50, 15), (255, 130, 35))
    if ctx.face == "top":
        for x in range(ctx.w):
            if ctx.rng.random() < 0.3:
                ctx.set(x, 0, (92, 78, 66))
    if core and ctx.face == "north":
        cx, cy = ctx.w // 2, ctx.h // 2 - 1
        for y in range(ctx.h):
            for x in range(ctx.w):
                d = math.hypot((x - cx) * 1.3, y - cy)
                if d < 3.2:
                    c = mix((255, 250, 210), (255, 150, 40), d / 3.2)
                    ctx.both(x, y, c)
        for k in range(4):
            ang = k * math.pi / 2 + ctx.rng.random() * 0.6
            x, y = cx, cy
            for step in range(8):
                x = int(round(cx + math.cos(ang) * step * 1.4))
                y = int(round(cy + math.sin(ang) * step))
                ctx.both(x, y, (255, 140, 40))
    if head and ctx.face == "north":
        ey = ctx.h // 2 - 1
        for dx in (-3, -2, 1, 2):
            ctx.both(ctx.w // 2 + dx, ey, (255, 210, 90))
        ctx.both(ctx.w // 2 - 3, ey - 1, (255, 170, 60))
        ctx.both(ctx.w // 2 + 2, ey - 1, (255, 170, 60))
        for dx in range(-2, 2):
            ctx.set(ctx.w // 2 + dx, ey - 2, (24, 18, 16))
        for dx in range(-2, 2):
            ctx.both(ctx.w // 2 + dx, ey + 4, (200, 80, 20))


def st_crystal(ctx):
    for y in range(ctx.h):
        t = y / max(1, ctx.h - 1)
        for x in range(ctx.w):
            c = mix((210, 250, 255), (40, 120, 190), t)
            if x == 0 and ctx.face in ("north", "west"):
                c = (245, 255, 255)
            ctx.both(x, y, c)


def st_void(ctx, head=False):
    fill_noise(ctx, VOID, 0.3, face_light(ctx.face))
    cracks(ctx, max(1, ctx.w * ctx.h // 70), 5, (70, 30, 130), (150, 70, 255))
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.rng.random() < 0.012:
                ctx.both(x, y, (235, 225, 255))
    if head and ctx.face == "north":
        cx = ctx.w // 2
        for y in range(1, ctx.h - 2):
            ctx.both(cx, y, (240, 220, 255) if 2 < y < ctx.h - 4 else (170, 90, 255))
            if ctx.rng.random() < 0.4:
                ctx.both(cx + ctx.rng.choice((-1, 1)), y, (150, 70, 255))
        for a in range(8):
            ang = a * math.pi / 4
            x = int(round(cx + math.cos(ang) * 2.6))
            y = int(round(ctx.h * 0.45 + math.sin(ang) * 2.6))
            ctx.both(x, y, (255, 255, 255))


def st_claw(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            t = y / max(1, ctx.h - 1)
            c = mix((150, 140, 175), (230, 225, 245), t)
            if ctx.face in ("north", "south", "east", "west") and x % 2 == 1 and y > ctx.h // 2:
                c = (0, 0, 0, 0)
            ctx.set(x, y, c)
    if ctx.face == "bottom":
        for x in range(ctx.w):
            ctx.glow_set(x, ctx.h // 2, (180, 110, 255))


def st_jelly_bell(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.face == "top":
                d = math.hypot(x - ctx.w / 2, y - ctx.h / 2) / (ctx.w / 2)
                c = mix((235, 160, 255, 200), (170, 120, 255, 170), d)
            elif ctx.face == "bottom":
                c = (140, 90, 220, 110)
            else:
                t = y / max(1, ctx.h - 1)
                c = mix((215, 140, 255, 185), (110, 190, 255, 135), t)
            n = ctx.n(x, y, 0.4)
            c = shade(c, 0.85 + n * 0.3)
            ctx.set(x, y, c)
            if ctx.rng.random() < 0.035:
                ctx.both(x, y, (255, 250, 255, 240))
    if ctx.face not in ("top", "bottom"):
        for x in range(ctx.w):
            ctx.glow_set(x, ctx.h - 1, (150, 220, 255))


def st_jelly_rim(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.face in ("north", "south", "east", "west") and y == ctx.h - 1 and x % 3 == 1:
                continue
            ctx.set(x, y, (120, 200, 255, 150))
            if y == 0:
                ctx.glow_set(x, y, (160, 230, 255))


def st_jelly_core(ctx):
    cx, cy = (ctx.w - 1) / 2, (ctx.h - 1) / 2
    for y in range(ctx.h):
        for x in range(ctx.w):
            d = math.hypot(x - cx, y - cy) / max(1, cx)
            ctx.both(x, y, mix((255, 245, 255), (255, 110, 215), min(1, d)))


def st_tentacle(ctx):
    for y in range(ctx.h):
        t = y / max(1, ctx.h - 1)
        for x in range(ctx.w):
            ctx.set(x, y, mix((215, 150, 255, 185), (120, 200, 255, 150), t))
            if y % 3 == 1:
                ctx.glow_set(x, y, (200, 170, 255))


def st_jelly_arm(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            edge = x in (0, ctx.w - 1) and (y + x) % 2 == 0
            if edge:
                continue
            ctx.set(x, y, mix((255, 170, 230, 175), (200, 140, 255, 140), y / max(1, ctx.h - 1)))
            if ctx.rng.random() < 0.1:
                ctx.glow_set(x, y, (255, 200, 240))


def seer_palette(ctx):
    elite = ctx.p.get("elite", False)
    robe = [(58, 12, 22), (80, 18, 30), (104, 26, 38), (128, 36, 48)] if elite else [(16, 10, 40), (24, 15, 58), (33, 21, 76), (44, 28, 96)]
    trim = (240, 196, 80) if elite else (214, 172, 74)
    return robe, trim


def st_robe(ctx, skirt=False, sleeve=False):
    robe, trim = seer_palette(ctx)
    for y in range(ctx.h):
        for x in range(ctx.w):
            fold = 0.85 + 0.2 * math.sin(x * 1.3 + ctx.n(x, y, 0.2) * 3)
            ctx.set(x, y, shade(ramp(robe, ctx.n(x, y, 0.3)), fold * face_light(ctx.face)))
    if ctx.face in ("north", "south", "east", "west"):
        if skirt or sleeve:
            for x in range(ctx.w):
                ctx.set(x, ctx.h - 1, trim)
                if sleeve:
                    ctx.set(x, ctx.h - 2, trim)
            if skirt:
                for x in range(ctx.w):
                    if x % 3 == 1:
                        ctx.both(x, ctx.h - 3, (120, 230, 255))
        if ctx.face == "north" and not sleeve:
            cx = ctx.w // 2
            for y in range(ctx.h):
                ctx.set(cx, y, trim)
                if skirt and y > 1:
                    ctx.set(cx - 1, y, shade(robe[0], 0.8))
            if not skirt:
                for y in range(2, ctx.h - 2, 3):
                    ctx.both(cx, y, (140, 235, 255))
                for x in range(ctx.w):
                    ctx.set(x, 0, trim)
    if sleeve and ctx.face == "bottom":
        for y in range(ctx.h):
            for x in range(ctx.w):
                ctx.set(x, y, (220, 205, 180) if 0 < x < ctx.w - 1 and 0 < y < ctx.h - 1 else robe[0])


def st_seer_face(ctx):
    robe, trim = seer_palette(ctx)
    if ctx.face == "north":
        for y in range(ctx.h):
            for x in range(ctx.w):
                c = mix((236, 218, 170), (200, 170, 110), y / max(1, ctx.h - 1))
                ctx.set(x, y, c)
        cx, cy = ctx.w // 2, ctx.h // 2 - 1
        for (dx, dy) in ((0, -2), (0, -1), (0, 1), (0, 2), (-1, 0), (-2, 0), (1, 0), (2, 0), (0, 0)):
            ctx.both(cx + dx - (1 if dx <= 0 and dy == 0 else 0), cy + dy, (255, 235, 150))
        ctx.both(cx - 1, cy, (255, 255, 255))
        for x in range(ctx.w):
            ctx.set(x, ctx.h - 1, trim)
        for (x, y) in ((1, 2), (ctx.w - 2, 2), (1, ctx.h - 3), (ctx.w - 2, ctx.h - 3)):
            ctx.set(x, y, (150, 120, 70))
    else:
        fill_noise(ctx, robe, 0.3, face_light(ctx.face))


def st_hood(ctx):
    robe, trim = seer_palette(ctx)
    if ctx.face == "bottom":
        return
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.face == "north" and 0 < x < ctx.w - 1 and y > 0:
                if x in (1, ctx.w - 2) or y == 1:
                    ctx.set(x, y, trim)
                continue
            ctx.set(x, y, shade(ramp(robe, ctx.n(x, y, 0.3)), face_light(ctx.face)))
    if ctx.face == "top":
        for x in range(ctx.w):
            if x % 4 == 2:
                ctx.both(x, ctx.h // 2, (140, 235, 255))


def st_orb(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.both(x, y, (150, 240, 255) if (x + y) % 2 else (230, 255, 255))


def st_gold_star(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.both(x, y, (255, 235, 150) if (x + y) % 2 else (255, 255, 230))


def st_teeth(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.face in ("north", "south", "east", "west"):
                tooth = (x % 2 == 0) or y == ctx.h - 1
                if not tooth and ctx.p.get("upper"):
                    tooth = y == 0
                if not tooth:
                    continue
            ctx.set(x, y, mix((250, 245, 225), (205, 195, 170), ctx.rng.random() * 0.5))


def st_tongue(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            c = (190, 45, 80) if x in (0, ctx.w - 1) else (225, 80, 110)
            if ctx.face == "top" and x == ctx.w // 2:
                c = (150, 30, 60)
            ctx.set(x, y, c)


def st_mimic_eye(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.both(x, y, (255, 210, 80))
    if ctx.face == "bottom":
        ctx.both(ctx.w // 2, ctx.h // 2, (20, 5, 5))
        ctx.set(ctx.w // 2, ctx.h // 2, (20, 5, 5))


def st_mimic_leg(ctx):
    fill_noise(ctx, [(40, 26, 20), (60, 40, 28), (82, 56, 38)], 0.5, face_light(ctx.face))
    if ctx.face == "bottom":
        for x in range(ctx.w):
            ctx.set(x, ctx.h // 2, (200, 190, 170))


def st_ray(ctx, part="body"):
    if ctx.face == "bottom":
        for y in range(ctx.h):
            for x in range(ctx.w):
                ctx.set(x, y, mix((210, 228, 245), (170, 195, 225), ctx.n(x, y, 0.3)))
        return
    fill_noise(ctx, NAVY, 0.25, face_light(ctx.face))
    if ctx.face == "top":
        for y in range(ctx.h):
            for x in range(ctx.w):
                if ctx.rng.random() < (0.05 if part != "tail" else 0.02):
                    ctx.both(x, y, (140, 245, 255))
        if part == "body":
            cx = ctx.w // 2
            for y in range(ctx.h):
                ctx.set(cx, y, (60, 90, 160))
                if y % 4 == 0:
                    ctx.both(cx, y, (190, 250, 255))
        if part in ("wing", "tip"):
            for y in range(ctx.h):
                ctx.both(ctx.w - 1 if ctx.p.get("left", True) else 0, y, (120, 235, 255))
            for x in range(ctx.w):
                ctx.both(x, 0, (120, 235, 255))
                ctx.both(x, ctx.h - 1, (90, 200, 255))
    else:
        for x in range(ctx.w):
            ctx.glow_set(x, 0, (90, 200, 255))


def st_ray_tip(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.both(x, y, (220, 255, 255) if (x + y) % 2 == 0 else (130, 240, 255))


def st_saddle(ctx):
    fill_noise(ctx, [(90, 50, 30), (118, 70, 40), (140, 88, 52)], 0.4, face_light(ctx.face))
    if ctx.face == "top":
        for x in range(ctx.w):
            ctx.set(x, 0, (230, 190, 80))
            ctx.set(x, ctx.h - 1, (230, 190, 80))


def st_astra_core(ctx):
    cx, cy = (ctx.w - 1) / 2, (ctx.h - 1) / 2
    for y in range(ctx.h):
        for x in range(ctx.w):
            d = math.hypot(x - cx, y - cy) / max(1, cx)
            swirl = 0.5 + 0.5 * math.sin(math.atan2(y - cy, x - cx) * 3 + d * 6)
            c = ramp([(255, 255, 240), (255, 230, 160), (255, 160, 90), (240, 110, 200)], min(1, d * 0.8 + swirl * 0.25))
            ctx.both(x, y, c)


def st_plate(ctx):
    fill_noise(ctx, OBSIDIAN, 0.3, face_light(ctx.face))
    gold = (196, 156, 70)
    for x in range(ctx.w):
        ctx.set(x, 0, gold)
        ctx.set(x, ctx.h - 1, gold)
    for y in range(ctx.h):
        ctx.set(0, y, gold)
        ctx.set(ctx.w - 1, y, gold)
    if ctx.w >= 6 and ctx.h >= 6:
        for i in range(min(ctx.w, ctx.h)):
            if i % 2 == 0:
                ctx.set(i, i, shade(gold, 0.8))
                ctx.set(ctx.w - 1 - i, i, shade(gold, 0.8))
        cx, cy = ctx.w // 2, ctx.h // 2
        glyph = [(0, -2), (0, -1), (0, 0), (0, 1), (0, 2), (-1, -1), (1, -1), (-2, 1), (2, 1)]
        for dx, dy in glyph:
            ctx.both(cx + dx, cy + dy, (190, 120, 255))


def st_astra_mask(ctx):
    if ctx.face != "north":
        fill_noise(ctx, OBSIDIAN, 0.35, face_light(ctx.face))
        return
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.set(x, y, mix((34, 22, 64), (18, 12, 36), y / max(1, ctx.h - 1)))
    gold = (214, 170, 80)
    for x in range(ctx.w):
        ctx.set(x, 0, gold)
    for y in range(ctx.h):
        ctx.set(0, y, gold)
        ctx.set(ctx.w - 1, y, gold)
    cx = ctx.w // 2
    eyes = [(cx - 3, 2), (cx - 2, 2), (cx + 1, 2), (cx + 2, 2), (cx - 1, 4), (cx, 4)]
    for x, y in eyes:
        ctx.both(x, y, (255, 250, 220))
    for x, y in ((cx - 3, 3), (cx + 2, 3), (cx - 1, 5), (cx, 5)):
        ctx.both(x, y, (255, 190, 90))
    for x in range(cx - 2, cx + 2):
        ctx.set(x, ctx.h - 2, (10, 6, 20))


def st_gold_spike(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            c = mix((255, 236, 150), (170, 110, 40), y / max(1, ctx.h - 1))
            ctx.set(x, y, c)
            if y < 2:
                ctx.glow_set(x, y, (255, 240, 180))


def st_astra_hand(ctx, finger=False):
    fill_noise(ctx, [(28, 16, 52), (40, 24, 72), (54, 34, 92), (66, 44, 110)], 0.35, face_light(ctx.face))
    cracks(ctx, max(1, ctx.w * ctx.h // 30), 4, (110, 60, 180), (190, 120, 255))
    if finger:
        for x in range(ctx.w):
            ctx.both(x, ctx.h - 1, (255, 220, 160))
        if ctx.face == "bottom":
            for y in range(ctx.h):
                for x in range(ctx.w):
                    ctx.both(x, y, (255, 230, 170))
    elif ctx.face == "north":
        for x in range(ctx.w):
            ctx.set(x, 1, (214, 170, 80))


def st_ring(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            c = (255, 214, 110) if (x + y) % 3 else (130, 240, 255)
            ctx.both(x, y, c)


def st_shard(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            c = mix((230, 200, 255), (120, 80, 230), y / max(1, ctx.h - 1))
            if x == 0:
                c = (245, 235, 255)
            ctx.both(x, y, c)


def st_streamer(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            a = 1 - y / max(1, ctx.h)
            ctx.both(x, y, mix((200, 140, 255), (60, 20, 120), 1 - a))


def st_meteor(ctx):
    fill_noise(ctx, [(20, 16, 15), (34, 27, 24), (48, 38, 33), (62, 50, 42)], 0.25, face_light(ctx.face))
    cracks(ctx, max(2, ctx.w * ctx.h // 25), 7, (180, 70, 20), (255, 150, 40))
    for y in range(ctx.h):
        for x in range(ctx.w):
            if ctx.rng.random() < 0.02:
                ctx.both(x, y, (255, 220, 120))


def st_hook(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            c = mix((210, 235, 245), (110, 150, 180), ctx.n(x, y, 0.6))
            ctx.set(x, y, c)
            if (x + y) % 3 == 0:
                ctx.glow_set(x, y, (150, 245, 255))


def st_sing_core(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            edge = x in (0, ctx.w - 1) or y in (0, ctx.h - 1)
            ctx.set(x, y, (70, 20, 120, 255) if edge else (4, 0, 10, 255))


def st_sing_shell(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            s = 0.5 + 0.5 * math.sin((x + y) * 0.9 + ctx.n(x, y, 0.5) * 4)
            ctx.set(x, y, (120 + int(60 * s), 50, 255, 60 + int(50 * s)))


def st_eyeball(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.set(x, y, mix((236, 232, 244), (200, 190, 215), ctx.n(x, y, 0.5)))
    for _ in range(2):
        x, y = ctx.rng.randrange(ctx.w), ctx.rng.randrange(ctx.h)
        for _ in range(4):
            ctx.set(x, y, (170, 40, 70))
            x += ctx.rng.choice((-1, 0, 1))
            y += ctx.rng.choice((-1, 0, 1))
    if ctx.face == "north":
        cx, cy = (ctx.w - 1) / 2, (ctx.h - 1) / 2
        for y in range(ctx.h):
            for x in range(ctx.w):
                d = math.hypot(x - cx, y - cy)
                if d < 1.2:
                    ctx.set(x, y, (10, 0, 20))
                    ctx.glow_set(x, y, (40, 0, 60))
                elif d < 3.3:
                    c = mix((220, 150, 255), (110, 40, 220), (d - 1.2) / 2.1)
                    ctx.both(x, y, c)


def st_halo(ctx):
    for y in range(ctx.h):
        for x in range(ctx.w):
            ctx.both(x, y, (255, 230, 150) if (x + y) % 2 else (255, 250, 220))


STYLES = {
    "wisp_core": st_wisp_core, "wisp_halo": st_wisp_halo, "mote": st_mote, "wisp_tail": st_wisp_tail,
    "rock": st_rock, "rock_torso": lambda c: st_rock(c, core=True), "rock_head": lambda c: st_rock(c, head=True),
    "crystal": st_crystal, "void": st_void, "void_head": lambda c: st_void(c, head=True), "claw": st_claw,
    "jelly_bell": st_jelly_bell, "jelly_rim": st_jelly_rim, "jelly_core": st_jelly_core, "tentacle": st_tentacle,
    "jelly_arm": st_jelly_arm, "robe": st_robe, "robe_skirt": lambda c: st_robe(c, skirt=True),
    "sleeve": lambda c: st_robe(c, sleeve=True), "seer_face": st_seer_face, "hood": st_hood, "orb": st_orb,
    "gold_star": st_gold_star, "teeth": st_teeth, "teeth_up": st_teeth, "tongue": st_tongue, "mimic_eye": st_mimic_eye,
    "mimic_leg": st_mimic_leg, "ray_body": lambda c: st_ray(c, "body"), "ray_wing_l": lambda c: st_ray(c, "wing"),
    "ray_wing_r": lambda c: st_ray(c, "wing"), "ray_fin": lambda c: st_ray(c, "fin"), "ray_tail": lambda c: st_ray(c, "tail"),
    "ray_tip": st_ray_tip, "saddle": st_saddle, "astra_core": st_astra_core, "plate": st_plate, "astra_mask": st_astra_mask,
    "gold_spike": st_gold_spike, "astra_hand": st_astra_hand, "finger": lambda c: st_astra_hand(c, finger=True),
    "ring": st_ring, "shard": st_shard, "streamer": st_streamer, "meteor": st_meteor, "hook": st_hook,
    "sing_core": st_sing_core, "sing_shell": st_sing_shell, "eyeball": st_eyeball, "halo": st_halo,
}


def paint(model, tex_name, params, seed):
    tw, th = model.tex
    base = Canvas(tw, th)
    glow = Canvas(tw, th)
    rng = random.Random(seed)
    noise = Noise(seed)
    for part, c in all_cubes(model.parts):
        style = STYLES[c.style]
        p = dict(params)
        if c.style == "teeth_up":
            p["upper"] = True
        if c.style == "ray_wing_r" or c.style == "ray_wing_l":
            p["left"] = c.style == "ray_wing_l"
        for face, (x, y, w, h) in face_rects(c).items():
            if w <= 0 or h <= 0:
                continue
            style(Ctx(base, glow, x, y, w, h, face, c, rng, noise, p))
    os.makedirs(TEX_DIR, exist_ok=True)
    base.save(os.path.join(TEX_DIR, f"{tex_name}.png"))
    if params.get("glow", True):
        glow.save(os.path.join(TEX_DIR, f"{tex_name}_glow.png"))


# ---------------------------------------------------------------------------------------------
# The models
# ---------------------------------------------------------------------------------------------

def circle(n, r, y, maker):
    return [maker(i, math.cos(i * 2 * math.pi / n) * r, y, math.sin(i * 2 * math.pi / n) * r, i * 2 * math.pi / n) for i in range(n)]


def models():
    ms = []

    # Star Wisp
    ms.append(Model("StarWisp", (64, 32), [
        Part("body", (0, 18, 0), cubes=[Cube((-3, -3, -3), (6, 6, 6), "wisp_core")]),
        Part("halo", (0, 18, 0), cubes=[Cube((-4, -4, -4), (8, 8, 8), "wisp_halo")]),
        Part("orbit", (0, 18, 0), children=[
            Part(f"mote{i}", (0, 0, 0), (0, i * math.pi / 2, 0), cubes=[Cube((5.5, -1, -1), (2, 2, 2), "mote")]) for i in range(4)]),
        Part("tail", (0, 19, 2.5), cubes=[Cube((-1.5, -1.5, 0), (3, 3, 3), "wisp_tail")], children=[
            Part("tail2", (0, 0, 3), cubes=[Cube((-1, -1, 0), (2, 2, 3), "wisp_tail")], children=[
                Part("tail3", (0, 0, 3), cubes=[Cube((-0.5, -0.5, 0), (1, 1, 3), "wisp_tail")])])]),
    ], [("star_wisp", {"glow": False})]))

    # Meteor Golem
    ms.append(Model("MeteorGolem", (128, 128), [
        Part("right_leg", (-6, 10, 0), cubes=[Cube((-4, 0, -4), (8, 14, 8), "rock")]),
        Part("left_leg", (6, 10, 0), cubes=[Cube((-4, 0, -4), (8, 14, 8), "rock")]),
        Part("torso", (0, 10, 0), cubes=[Cube((-12, -22, -7), (24, 22, 14), "rock_torso")], children=[
            Part("head", (0, -20, -5), cubes=[Cube((-5, -8, -6), (10, 9, 10), "rock_head")]),
            Part("right_arm", (-14, -18, 0), cubes=[Cube((-5, -2, -5), (9, 34, 9), "rock")], children=[
                Part("right_rock", (0, 0, 0), cubes=[Cube((-6, -5, -6), (11, 6, 11), "rock")])]),
            Part("left_arm", (14, -18, 0), cubes=[Cube((-4, -2, -5), (9, 34, 9), "rock")], children=[
                Part("left_rock", (0, 0, 0), cubes=[Cube((-5, -5, -6), (11, 6, 11), "rock")])]),
            Part("crystals", (0, -20, 5), children=[
                Part("crystal0", (-6, 0, 0), (-0.45, 0, -0.35), cubes=[Cube((-1.5, -10, -1.5), (3, 10, 3), "crystal")]),
                Part("crystal1", (1, 0, 1), (-0.3, 0, 0.1), cubes=[Cube((-2, -14, -2), (4, 14, 4), "crystal")]),
                Part("crystal2", (7, 0, 0), (-0.45, 0, 0.45), cubes=[Cube((-1, -8, -1), (2, 8, 2), "crystal")]),
            ]),
        ]),
    ], [("meteor_golem", {})]))

    # Void Stalker
    ms.append(Model("VoidStalker", (64, 64), [
        Part("right_leg", (-2.5, 2, 0), cubes=[Cube((-1.5, 0, -1.5), (3, 22, 3), "void")]),
        Part("left_leg", (2.5, 2, 0), cubes=[Cube((-1.5, 0, -1.5), (3, 22, 3), "void")]),
        Part("torso", (0, 2, 0), cubes=[Cube((-4.5, -16, -2.5), (9, 18, 5), "void")], children=[
            Part("head", (0, -16, 0), cubes=[Cube((-3.5, -10, -3.5), (7, 10, 7), "void_head")]),
            Part("right_arm", (-6, -14, 0), cubes=[Cube((-1.5, -1, -1.5), (3, 27, 3), "void")], children=[
                Part("right_claw", (0, 26, 0), cubes=[Cube((-1.5, 0, -1.5), (3, 5, 3), "claw")])]),
            Part("left_arm", (6, -14, 0), cubes=[Cube((-1.5, -1, -1.5), (3, 27, 3), "void")], children=[
                Part("left_claw", (0, 26, 0), cubes=[Cube((-1.5, 0, -1.5), (3, 5, 3), "claw")])]),
        ]),
    ], [("void_stalker", {})]))

    # Nebula Jelly
    tentacles = []
    for i in range(8):
        a = i * math.pi / 4
        tentacles.append(Part(f"tentacle{i}", (math.cos(a) * 6.5, 2, math.sin(a) * 6.5), cubes=[Cube((-0.5, 0, -0.5), (1, 7, 1), "tentacle")],
                              children=[Part("seg", (0, 7, 0), cubes=[Cube((-0.5, 0, -0.5), (1, 7, 1), "tentacle")],
                                             children=[Part("tip", (0, 7, 0), cubes=[Cube((-0.5, 0, -0.5), (1, 6, 1), "tentacle")])])]))
    ms.append(Model("NebulaJelly", (128, 64), [
        Part("bell", (0, 4, 0), cubes=[Cube((-7, -9, -7), (14, 9, 14), "jelly_bell"), Cube((-8, 0, -8), (16, 2, 16), "jelly_rim")],
             children=[Part("core", (0, -4, 0), cubes=[Cube((-3, -3, -3), (6, 6, 6), "jelly_core")])] + tentacles + [
                 Part("arm0", (-2, 2, 0), cubes=[Cube((-1.5, 0, -0.5), (3, 14, 1), "jelly_arm")]),
                 Part("arm1", (2, 2, 0), (0, 1.57, 0), cubes=[Cube((-1.5, 0, -0.5), (3, 14, 1), "jelly_arm")]),
             ]),
    ], [("nebula_jelly", {})]))

    # Starseer
    stars = [Part(f"star{i}", (math.cos(i * 2 * math.pi / 5 - math.pi / 2) * 5, math.sin(i * 2 * math.pi / 5 - math.pi / 2) * 5, 0),
                  (0, 0, 0.785), cubes=[Cube((-1, -1, -0.5), (2, 2, 1), "gold_star")]) for i in range(5)]
    ms.append(Model("Starseer", (64, 64), [
        Part("head", (0, 0, 0), cubes=[Cube((-4, -8, -4), (8, 8, 8), "seer_face")], children=[
            Part("hood", (0, 0, 0), cubes=[Cube((-4.5, -8.6, -4.6), (9, 9, 9), "hood")]),
            Part("halo", (0, -6, 5), children=stars),
        ]),
        Part("body", (0, 0, 0), cubes=[Cube((-4, 0, -3), (8, 12, 6), "robe")]),
        Part("skirt", (0, 12, 0), cubes=[Cube((-5, 0, -4), (10, 12, 8), "robe_skirt")]),
        Part("right_arm", (-5, 2, 0), cubes=[Cube((-3, -2, -2), (4, 12, 4), "sleeve")], children=[
            Part("orb", (-1, 11, -1), cubes=[Cube((-1.5, -1.5, -1.5), (3, 3, 3), "orb")])]),
        Part("left_arm", (5, 2, 0), cubes=[Cube((-1, -2, -2), (4, 12, 4), "sleeve")]),
    ], [("starseer", {}), ("high_starseer", {"elite": True, "glow": False})]))

    # Astral Mimic innards (the chest shell uses the vanilla chest layout, see AstralMimicModel)
    ms.append(Model("AstralMimicInnards", (64, 64), [
        Part("base_in", (0, 24, 0), children=[
            Part("teeth_front", (0, 0, 0), cubes=[Cube((-6, -12, -6.5), (12, 2, 1), "teeth")]),
            Part("teeth_back", (0, 0, 0), cubes=[Cube((-6, -12, 5.5), (12, 2, 1), "teeth")]),
            Part("teeth_left", (0, 0, 0), cubes=[Cube((5.5, -12, -5.5), (1, 2, 11), "teeth")]),
            Part("teeth_right", (0, 0, 0), cubes=[Cube((-6.5, -12, -5.5), (1, 2, 11), "teeth")]),
            Part("tongue", (0, -10, 4), cubes=[Cube((-2, -1, -9), (4, 1, 9), "tongue")]),
        ]),
        Part("lid_in", (0, 14, 7), children=[
            Part("teeth_upper_front", (0, 0, 0), cubes=[Cube((-6, 0, -13.5), (12, 2, 1), "teeth_up")]),
            Part("teeth_upper_left", (0, 0, 0), cubes=[Cube((5.5, 0, -12.5), (1, 2, 11), "teeth_up")]),
            Part("teeth_upper_right", (0, 0, 0), cubes=[Cube((-6.5, 0, -12.5), (1, 2, 11), "teeth_up")]),
            Part("eye_l", (0, 0, 0), cubes=[Cube((-5, -0.5, -10), (3, 1, 3), "mimic_eye")]),
            Part("eye_r", (0, 0, 0), cubes=[Cube((2, -0.5, -10), (3, 1, 3), "mimic_eye")]),
        ]),
    ] + [Part(f"leg{i}", (sx * 5, 21, sz * 5), cubes=[Cube((-1.5, 0, -1.5), (3, 4, 3), "mimic_leg")])
         for i, (sx, sz) in enumerate(((-1, -1), (1, -1), (-1, 1), (1, 1)))],
        [("astral_mimic", {})]))

    # Comet Ray
    ms.append(Model("CometRay", (128, 64), [
        Part("body", (0, 19, 0), cubes=[Cube((-5, -2.5, -9), (10, 4, 18), "ray_body")], children=[
            Part("fin_l", (3, 0, -9), (0, -0.25, 0), cubes=[Cube((-0.5, -1, -5), (2, 2, 5), "ray_fin")]),
            Part("fin_r", (-3, 0, -9), (0, 0.25, 0), cubes=[Cube((-1.5, -1, -5), (2, 2, 5), "ray_fin")]),
            Part("wing_l", (5, 0, -2), cubes=[Cube((0, -0.5, -7), (10, 1, 13), "ray_wing_l")], children=[
                Part("wing_l_tip", (10, 0, 0), cubes=[Cube((0, -0.5, -5), (9, 1, 9), "ray_wing_l")])]),
            Part("wing_r", (-5, 0, -2), cubes=[Cube((-10, -0.5, -7), (10, 1, 13), "ray_wing_r")], children=[
                Part("wing_r_tip", (-10, 0, 0), cubes=[Cube((-9, -0.5, -5), (9, 1, 9), "ray_wing_r")])]),
            Part("tail", (0, 0, 9), cubes=[Cube((-0.5, -0.5, 0), (1, 1, 10), "ray_tail")], children=[
                Part("tail_mid", (0, 0, 10), cubes=[Cube((-0.5, -0.5, 0), (1, 1, 10), "ray_tail")], children=[
                    Part("tail_tip", (0, 0, 10), cubes=[Cube((-1, -1, -1), (2, 2, 2), "ray_tip")])])]),
            Part("saddle", (0, -2.5, -1), cubes=[Cube((-3, -1, -3), (6, 1, 7), "saddle")]),
        ]),
    ], [("comet_ray", {})]))

    # Astraeon
    def finger(i, side):
        return Part(f"finger{i}", (-2.25 + 1.5 * i, 2, -2.5), (0.35, 0, 0), cubes=[Cube((-0.5, 0, -0.5), (1, 5, 1), "finger")])

    def hand(name, x, side):
        return Part(name, (x, 6, -3), cubes=[Cube((-3, -2, -3), (6, 4, 6), "astra_hand")],
                    children=[finger(i, side) for i in range(4)] + [
                        Part("thumb", (3 * side, 0, -1), (0, 0, -0.6 * side), cubes=[Cube((-0.5, 0, -0.5), (1, 4, 1), "finger")])])

    ring_a = [Part(f"seg{i}", (math.cos(i * math.pi / 6) * 12, 0, math.sin(i * math.pi / 6) * 12), (0, -i * math.pi / 6 + math.pi / 2, 0),
                   cubes=[Cube((-2, -0.5, -0.5), (4, 1, 1), "ring")]) for i in range(12)]
    ring_b = [Part(f"seg{i}", (math.cos(i * math.pi / 8) * 15, 0, math.sin(i * math.pi / 8) * 15), (0, -i * math.pi / 8 + math.pi / 2, 0),
                   cubes=[Cube((-2.5, -0.5, -0.5), (5, 1, 1), "ring")]) for i in range(16)]
    shard_parts = [Part(f"shard{i}", (math.cos(i * math.pi / 3) * 8.5, math.sin(i * 1.7) * 3, math.sin(i * math.pi / 3) * 8.5),
                        (0.3, i * 0.9, 0.2), cubes=[Cube((-1, -2, -1), (2, 4, 2), "shard")]) for i in range(6)]
    ms.append(Model("Astraeon", (128, 128), [
        Part("core", (0, 4, 0), cubes=[Cube((-5, -5, -5), (10, 10, 10), "astra_core")]),
        Part("shell", (0, 4, 0), children=[
            Part("plate_front", (0, 0, 0), cubes=[Cube((-6, -6, -7), (12, 12, 2), "plate")]),
            Part("plate_back", (0, 0, 0), cubes=[Cube((-6, -6, 5), (12, 12, 2), "plate")]),
            Part("plate_left", (0, 0, 0), cubes=[Cube((5, -6, -5), (2, 12, 10), "plate")]),
            Part("plate_right", (0, 0, 0), cubes=[Cube((-7, -6, -5), (2, 12, 10), "plate")]),
            Part("plate_top", (0, 0, 0), cubes=[Cube((-5, -7, -5), (10, 2, 10), "plate")]),
            Part("plate_bottom", (0, 0, 0), cubes=[Cube((-5, 5, -5), (10, 2, 10), "plate")]),
        ]),
        Part("mask", (0, -4, -4), cubes=[Cube((-4, -7, -2), (8, 8, 3), "astra_mask")], children=[
            Part("spike0", (0, -7, 0), (-0.1, 0, 0), cubes=[Cube((-1, -8, -1), (2, 8, 2), "gold_spike")]),
            Part("spike1", (-2.5, -6.5, 0), (-0.1, 0, -0.45), cubes=[Cube((-0.5, -6, -0.5), (1, 6, 1), "gold_spike")]),
            Part("spike2", (2.5, -6.5, 0), (-0.1, 0, 0.45), cubes=[Cube((-0.5, -6, -0.5), (1, 6, 1), "gold_spike")]),
            Part("spike3", (-4, -5, 0), (0, 0, -0.9), cubes=[Cube((-0.5, -5, -0.5), (1, 5, 1), "gold_spike")]),
            Part("spike4", (4, -5, 0), (0, 0, 0.9), cubes=[Cube((-0.5, -5, -0.5), (1, 5, 1), "gold_spike")]),
        ]),
        hand("left_hand", 11, 1),
        hand("right_hand", -11, -1),
        Part("ring_a", (0, 4, 0), (0.2, 0, 0.1), children=ring_a),
        Part("ring_b", (0, 4, 0), (1.1, 0, 0.4), children=ring_b),
        Part("shards", (0, 4, 0), children=shard_parts),
        Part("streamers", (0, 10, 0), children=[
            Part(f"streamer{i}", (x, 0, 2), cubes=[Cube((-0.5, 0, -0.5), (1, 12, 1), "streamer")]) for i, x in enumerate((-3, 0, 3))]),
    ], [("astraeon", {})]))

    # Projectiles and small parts
    ms.append(Model("Meteor", (128, 64), [
        Part("rock", (0, 0, 0), cubes=[Cube((-8, -8, -8), (16, 16, 16), "meteor"), Cube((-9.5, -4, -3), (2, 6, 6), "meteor"),
                                        Cube((7, -5, -4), (3, 7, 7), "meteor"), Cube((-4, -10, -5), (8, 3, 8), "meteor"),
                                        Cube((-3, 7.5, -4), (7, 3, 7), "meteor")]),
    ], [("meteor", {})]))
    ms.append(Model("MoltenRock", (64, 32), [
        Part("rock", (0, 0, 0), cubes=[Cube((-4, -4, -4), (8, 8, 8), "meteor"), Cube((-5, -2, -2), (2, 4, 4), "meteor")]),
    ], [("molten_rock", {})]))
    ms.append(Model("TetherHook", (32, 32), [
        Part("hook", (0, 0, 0), cubes=[Cube((-1.5, -1.5, -1.5), (3, 3, 3), "hook")], children=[
            Part(f"prong{i}", (0, 0, 0), (0.6 * math.cos(i * math.pi / 2), 0, 0.6 * math.sin(i * math.pi / 2)),
                 cubes=[Cube((-0.5, -0.5, -4), (1, 1, 3), "hook")]) for i in range(4)]),
    ], [("tether_hook", {"glow": False})]))
    ms.append(Model("Singularity", (64, 64), [
        Part("core", (0, 0, 0), cubes=[Cube((-4, -4, -4), (8, 8, 8), "sing_core")]),
        Part("shell", (0, 0, 0), cubes=[Cube((-5, -5, -5), (10, 10, 10), "sing_shell")]),
    ], [("singularity", {"glow": False})]))
    ms.append(Model("SentinelEye", (32, 16), [
        Part("eye", (0, 0, 0), cubes=[Cube((-3.5, -3.5, -3.5), (7, 7, 7), "eyeball")]),
    ], [("sentinel_eye", {})]))
    halo_segs = [Part(f"seg{i}", (math.cos(i * math.pi / 8) * 5, 0, math.sin(i * math.pi / 8) * 5), (0, -i * math.pi / 8 + math.pi / 2, 0),
                      cubes=[Cube((-1, -0.5, -0.5), (2, 1, 1), "halo")]) for i in range(16)]
    ms.append(Model("Halo", (32, 32), [
        Part("halo", (0, 0, 0), children=halo_segs + [
            Part(f"point{i}", (math.cos(i * math.pi / 3) * 5, -1, math.sin(i * math.pi / 3) * 5), (0, 0, 0),
                 cubes=[Cube((-0.5, -1, -0.5), (1, 2, 1), "halo")]) for i in range(6)]),
    ], [("halo", {"glow": False})]))
    return ms


def main():
    for i, m in enumerate(models()):
        pack(m)
        emit_java(m)
        for j, (tex, params) in enumerate(m.textures):
            paint(m, tex, params, seed=1000 + i * 17 + j)
        print(f"{m.cls}: {sum(1 for _ in all_cubes(m.parts))} cubes -> {', '.join(t for t, _ in m.textures)}")


if __name__ == "__main__":
    main()
